Endpoint /versions made more robust
The following error was reported

2024-08-27 12:50:55.025 ERROR 31489 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 81] with root cause
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 81
    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[na:na]
    at java.base/java.lang.String.substring(String.java:2707) ~[na:na]
    at com.ericsson.eiffel.remrem.generate.controller.VersionService.getServiceVersion(VersionService.java:113) ~[classes/:na]
    at com.ericsson.eiffel.remrem.generate.controller.VersionService.getMessagingVersions(VersionService.java:95) ~[classes/:na]
    at com.ericsson.eiffel.remrem.generate.controller.RemremGenerateController.getVersions(RemremGenerateController.java:410) ~[classes/:na]

This fix handles -1 result of lastIndexOf properly, so no exception is
thrown.